_target_: main.Main

proj_name: hydra_template
username: your_username
mlflow_pass: your_pass

defaults:
  # Main
  - _self_
  - exp: myexp

seed: 47
debug: false

## Output dir
hydra:
  run:
    dir: data/${proj_name}_outputs/${exp._target_}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: data/${proj_name}_multirun/${exp._target_}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job: # squeue
    name: ${proj_name}_${exp._target_}
