_target_: main.Main

defaults:
  - main_local

## Output dir
hydra:
  launcher:
    timeout_min: 2880
    nodes: 1
    tasks_per_node: 1
    cpus_per_task: 8
    mem_per_cpu: 1024M
    gres: gpu:1
    partition: long-disi
    additional_parameters:
      mail_type: END,FAIL
